towfood2/urls.py
from rest_framework import routers
from django.contrib import admin
from django.urls import path, include
from app1 import views

router = routers.DefaultRouter()
router.register(r'products', views.ProductViewSet)


urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('', views.home, name="home"),
    path('login/', views.login_view, name="login"),
    path('stock/', views.stock, name="stock"),
    path('total_stock/', views.total_stock, name="total_stock"),
    path('scan_in_1/', views.scan_in_1, name="scan_in"),
    path('scan_in/', views.add_product, name="scan_in"),
    path('addProduct/', views.add_product, name="add_product"),
    path('scan_out/', views.scan_out, name="scan_out"),
    path('scan_out_1/', views.scan_out_1, name="scan_out"),
    path('people/', views.people, name="people"),
    path('members/', views.members, name="members"),
    path('search/<q>', views.searchAjax, name="search"),
    path('p_search/<p>', views.p_search, name="p_search"),
    path('add_member/', views.add_member, name="add_member"),
    path('reports/', views.reports, name="reports"),
    path('larder_report/', views.larder_report, name="larder_report"),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('admin/',admin.site.urls),

]
 

app1/models.py
from unicodedata import category
from django.db import models
from django import forms
from django.contrib.postgres.fields import ArrayField
from django.core.validators import RegexValidator


# Model Objects

# Product Ingoing (Collections)
class Product(models.Model):
    id = models.AutoField(primary_key=True)
    brand = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    barcode = models.IntegerField()
    category= models.CharField(max_length=500)
    perishable = models.BooleanField(default=False)
    allergens = models.CharField(max_length=500)
    weight = models.FloatField(default=0)
    quantity = models.IntegerField(default=1)
    footprint = models.FloatField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    collection = models.ForeignKey('Collection', on_delete=models.CASCADE, null=True)
    
    def category_list(self):
        return self.category.split(',')

# Product Outgoing (Pickups)
class ProductOut(models.Model):
    id = models.AutoField(primary_key=True)
    brand = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    barcode = models.IntegerField()
    category= models.CharField(max_length=500)
    perishable = models.BooleanField(default=False)
    allergens = models.CharField(max_length=500)
    weight = models.FloatField(default=0)
    quantity = models.IntegerField(default=1)
    footprint = models.FloatField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    pickup = models.ForeignKey('Pickup', on_delete=models.CASCADE, null=True)
    
    def category_list(self):
        return self.category.split(',')

# Member Data
class Member(models.Model):
    id = models.AutoField(primary_key=True)
    firstName = models.CharField(max_length=100)
    lastName = models.CharField(max_length=100)
    addressFirstLine = models.CharField(max_length=500)
    ageGroup = models.CharField(max_length=100)
    ethnicity = models.CharField(max_length=100)
    postCode = models.CharField(max_length=100)
    # phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    # phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True) # Validators should be a list
    email = models.EmailField(max_length=100)
    prefContact = models.CharField(max_length=100)
    occupation = models.CharField(max_length=100)
    isCarer = models.BooleanField(default=False)
    isMember = models.BooleanField(default=True)
    isEmployed = models.BooleanField(default=True)
    noAdults = models.IntegerField(default=0)
    noChildren = models.IntegerField(default=0)
    foodAllergies = models.CharField(max_length=300)
    prefLarder = models.ForeignKey('Larder', on_delete=models.CASCADE, null=True)
    acceptedPolicy = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    totalFoodCollected = models.FloatField(default=0)
    baselineHealthScore = models.FloatField(default=0)
    currentHealthScore = models.FloatField(default=0)

    def __str__(self):
        return self.firstName + " " + self.lastName

# Volunteer Data    
class Volunteer(models.Model):
    id = models.AutoField(primary_key=True)
    firstName = models.CharField(max_length=100)
    lastName = models.CharField(max_length=100)
    addressFirstLine = models.CharField(max_length=500)
    postCode = models.CharField(max_length=100)
    # phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    # phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True) # Validators should be a list
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=100)
    isAdmin = models.BooleanField(default=False)
    age = models.IntegerField(default=0)
    prefLarder = models.ForeignKey('Larder', on_delete=models.CASCADE, null=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.firstName + " " + self.lastName

# Supplier Data    
class Supplier(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    addressFirstLine = models.CharField(max_length=500)
    postCode = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name + " " + self.addressFirstLine

# Larder Data
class Larder(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    addressFirstLine = models.CharField(max_length=500)
    postCode = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

# Updating the list of products at a specific larder
class Update(models.Model):
    id = models.AutoField(primary_key=True)
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    larder = models.ForeignKey(Larder, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "member:" + str(self.member) + "larder:" + str(self.larder) + "product:" + str(self.product) + "created_at:" + str(self.created_at) + "time:" + str(self.time)

#(Ingoing) Collection is when a volunteer collects products from a supplier to be stored in a larder
class Collection(models.Model):
    id = models.AutoField(primary_key=True)
    volunteer = models.ForeignKey(Volunteer, on_delete=models.CASCADE)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE)
    larder = models.ForeignKey(Larder, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.volunteer.firstName + " | " + self.supplier.name + " " + self.supplier.addressFirstLine + " -> " + self.larder.name + " | " + str(self.created_at)

# (Outgoing) Pickup is when a member picks up products from a larder
class Pickup(models.Model):
    id = models.AutoField(primary_key=True)
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    larder = models.ForeignKey(Larder, on_delete=models.CASCADE)
    volunteer = models.ForeignKey(Volunteer, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.volunteer.firstName + " | " + self.larder.name + " -> " + self.member.lastName + " | " + str(self.created_at)

app1/forms.py
from django import forms
from app1.models import *

class addProd(forms.ModelForm):
    class Meta:
        model = Product
        fields = ("collection","id", "brand", "name", "barcode","category","allergens", "weight", "quantity", "footprint","perishable")
        widgets = {
            # 'collection': forms.HiddenInput(),
            'barcode': forms.HiddenInput(),
            # 'quantity': forms.HiddenInput()
        }

class pickupProd(forms.ModelForm):
    class Meta:
        model = ProductOut
        fields = ("pickup","id", "brand", "name", "barcode","category","allergens", "weight", "quantity", "footprint","perishable")
        widgets = {
            # 'pickup': forms.HiddenInput(),
            'barcode': forms.HiddenInput(),
            # 'quantity': forms.HiddenInput()
        }
class addCollection(forms.ModelForm):
    class Meta:
        model = Collection
        fields = ("id", "volunteer", "supplier", "larder")

class addPickup(forms.ModelForm):
    class Meta:
        model = Pickup
        fields = ("id", "volunteer", "larder", "member")


class createReport(forms.Form):
    start_date = forms.DateField(label="Start Date", widget=forms.SelectDateWidget(years=range(2016,2022)))
    end_date = forms.DateField(label="End Date", widget=forms.SelectDateWidget(years=range(2016,2022)))

app1/templates/add_member.html
{% extends "layout.html" %}
{% block title %}
Add Member
{% endblock %}
{% block content %}
<div class="flex flex-col space-y-7">
  <!-- Heading -->
  <div class="flex justify-center align-middle text-3xl font-bold pt-3 space-x-2">
    <h1>Towcester</h1>
    <div class="dropdown dropdown-end">
      <label tabindex="0" class="cursor-pointer"><i class="fa-solid fa-caret-down fa-sm pt-1"></i></label>
      <ul tabindex="0" class="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52">
        <li class="active"><a>Towcester</a></li>
        <li><a>Roade</a></li>
      </ul>
    </div>
  </div>
  <!-- Content -->
  <div class="flex flex-col justify-center items-center">
    <!-- Stock Card -->
    <div class="avatar">
      <div class="w-24 mask mask-squircle z-10">
        <img src="https://placeimg.com/192/192/people" />
      </div>
    </div>
    <div class="card bg-base-200 shadow-2xl w-auto flex justify-center -mt-7">
      <div class="flex flex-row items-center align-middle space-x-2 px-7 py-10">
        <div class="flex flex-col">
          <input type="text" placeholder="First Name" class="input input-ghost w-full max-w-xs" />
          <select class="select input-ghost select-ghost w-full max-w-xs">
            <option disabled selected>Pref Larder</option>
            <option>Towcester</option>
            <option>Roade</option>
          </select> 
          <input type="text" placeholder="Address" class="input input-ghost w-full max-w-xs" />
          <input type="text" placeholder="Post Code" class="input input-ghost w-full max-w-xs" />
          <input type="text" placeholder="Occupation" class="input input-ghost w-full max-w-xs" />
          <label class="input input-ghost cursor-pointer w-full ">
            <span class="input-ghost">Carer?</span> 
            <input type="checkbox" checked="checked" class="checkbox checkbox-xs" />
          </label>
          <label class="input input-ghost cursor-pointer w-full ">
            <span class="input-ghost">Member?</span> 
            <input type="checkbox" checked="checked" class="checkbox checkbox-xs" />
          </label>
          <label class="input input-ghost cursor-pointer w-full ">
            <span class="input-ghost">Employed?</span> 
            <input type="checkbox" checked="checked" class="checkbox checkbox-xs" />
          </label>
          <label class="input input-ghost cursor-pointer w-full ">
            <span class="input-ghost">Accepted Policies?</span> 
            <input type="checkbox" checked="checked" class="checkbox checkbox-xs" />
          </label>          
        </div>
        <div class="flex flex-col">
          <input type="text" placeholder="Last Name" class="input input-ghost w-full max-w-xs" />
          <select class="select input-ghost select-ghost w-full max-w-xs">
            <option disabled selected>Pref Contact</option>
            <option>Phone</option>
            <option>Email</option>
          </select>          
          <input type="tel" placeholder="Phone Number" class="input input-ghost w-full max-w-xs" />
          <input type="email" placeholder="Email" class="input input-ghost w-full max-w-xs" />
          <input type="number" placeholder="Adults" class="input input-ghost w-full max-w-xs" />
          <input type="number" placeholder="Children" class="input input-ghost w-full max-w-xs" />
          <input type="text" placeholder="Allergies" class="input input-ghost w-full max-w-xs" />
          <input type="text" placeholder="Current Health Score" class="input input-ghost w-full max-w-xs" disabled/>
          <input type="text" placeholder="Total Food Collected" class="input input-ghost w-full max-w-xs" disabled/>
        </div> 
    </div>
  </div>
    

<!-- Bottom Nav -->
<div class="btm-nav bg-base-200">
  <button  class="active">
    <i class="fa-solid fa-house"></i>
  </button>
  <button>
    <i class="fa-solid fa-cart-shopping"></i>
  </button>
  <button>
    <i class="fa-solid fa-users"></i>
  </button>
  <button>
    <i class="fa-solid fa-bars"></i>
  </button>
</div>
{% endblock %}

app1/templates/home.html
{% extends "layout.html" %}
{% block title %}
Home
{% endblock %}
{% block content %}
<div class="flex flex-col space-y-7">
  <!-- Heading -->
  <div class="flex justify-center align-middle text-3xl font-bold pt-3 space-x-2">
    <h1>Towcester</h1>
  </div>
  <!-- Content -->
  <div class="flex justify-center">
    <!-- Stock Card -->
    <div class="card card-side bg-base-200 shadow-2xl w-96 flex justify-center cursor-pointer" onclick="location.href = '/total_stock'">
      <div class="h-44 w-48 pl-5">
        <canvas id="stockPie"></canvas>
      </div>
      <div class="card-body align-middle items-center">
        <h3 class="card-title">Total Stock</h3>
        <p class="card-text text-4xl font-bold">{{ total_weight_in }}g</p>
      </div>
    </div>
  </div>
    <!-- Info Cards -->
    <div class="flex justify-center space-x-7">
      <div class="card bg-base-200 shadow-2xl w-44 flex justify-center">
        <div class="card-body items-center">
          <h3 class="card-title">Members</h3>
          <p class="card-text text-4xl font-bold">450</p>
        </div>
      </div>
      <div class="card bg-base-200 shadow-2xl w-44 flex justify-center">
        <div class="card-body flex items-center">
          <h3 class="card-title">Volunteers</h3>
          <p class="card-text text-4xl font-bold">450</p>
        </div>
      </div>
    </div>
    <div class="flex justify-center">
      <div class="indicator">
        <span class="indicator-item badge badge-secondary">5</span> 
        <div class="card  bg-base-200 shadow-2xl w-96 flex justify-center">
          <div class="card-body align-middle">
            <h3 class="card-title">Stock Warnings</h3>
            <ul id="stock-warnings">
              <li>Potatos</li>
              <li>Beans</li>
              <li>Cheese</li>
              <li>Bacon</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

app1/templates/larder_report.html
{% load tailwind_tags %} {% load tailwind_filters %}
<html lang="en" data-theme="light">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Larder Report</title>

    {% load static %}
    {% tailwind_css %}
    <script src="{% static 'myJS.js' %}" defer></script>
    <script src="{% static 'MyQuagga.js' %}" defer></script>
    <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="stylesheet" href="{% static 'myCSS.css' %}" />
  </head>
  <body c>
    <div class="flex p-10 justify-center">
        <div class="flex flex-col space-y-5 justify-center items-center">
            <img class="w-1/3" src="https://static.wixstatic.com/media/40f4b2_957f85af43e3430e9ac31b61049d3c18~mv2.png/v1/fill/w_168,h_94,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/TowFood-Logo.png" alt="">
            <h1 class="text-4xl font-bold">Larder Report</h1>
        </div>
    </div>
    <div class="flex p-10 flex-col">
        <div class="flex flex-row space-x-3">
            <h2 class="text-2xl font-bold">{{ larder_name }}</h2>
            <h2 class="text-2xl">|</h2>
            <h2 class="text-2xl">{{ start_date }} - {{ end_date }}</h2>
        </div>
        <div class="divider">
            <h3 class="text-xl">Overview</h3>
        </div>
        <div class="flex flex-row space-x-40  justify-center">
            <div class="flex flex-col space-y-3">
                <div class="flex flex-row space-x-3 ">
                    <h3 class="text-xl align-top">Larder Address:</h3>
                    <p>{{ larder_address }}</p>
                </div>
                <div class="flex flex-row space-x-3 ">
                    <h3 class="text-xl align-top">New Members:</h3>
                    <p>{{ new_members }}</p>
                </div>
                <div class="flex flex-row space-x-3 ">
                    <h3 class="text-xl align-top">New Volunteers:</h3>
                    <p>{{ new_volunteers }}</p>
                </div>
            </div>
            <div class="flex flex-col space-y-3">
                <div class="flex flex-row space-x-3 ">
                    <h3 class="text-xl align-top">Total Stock In:</h3>
                    <p>{{ total_weight_in }}g</p>
                </div>
                <div class="flex flex-row space-x-3 ">
                    <h3 class="text-xl align-top">Total Stock Out:</h3>
                    <p>{{ total_weight_out }}g</p>
                </div>
                <div class="flex flex-row space-x-3 ">
                    <h3 class="text-xl align-top">Largest Supplier:</h3>
                    <p>{{ largest_supplier }}</p>
                </div>
            </div>
        </div>
        <!-- Suppliers -->
        <div class="divider">
            <h3 class="text-xl">Suppliers</h3>
        </div>
        <div>
            <table class="table table-compact w-full px-4 ">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Location</th>
                    <th>Type</th>
                    <th>Stock Provided</th>
                  </tr>
                </thead>
                <tbody>
                  {% for x in supplier_data %}
                  <tr>
                    <td>{{ x.name }}</td>
                    <td>{{ x.addressFirstLine }} </td>
                    <td>{{ x.type }}</td>
                    <!-- total stock provided -->
                    <td>{{ x.TotalWeight }}g</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
        </div>
        <!-- Members -->
        <div class="divider">
            <h3 class="text-xl">Members</h3>
        </div>
        <div>
            <table class="table table-compact w-full px-4">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Size of Household</th>
                    <th>Stock taken</th>
                  </tr>
                </thead>
                <tbody>
                  {% for x in member_data %}
                  <tr>
                    <th>{{ x.id }}</th>
                    <td>{{ x.firstName }} {{ x.lastName }} </td>
                    <td>{{ x.numInHousehold }} </td>
                    <td>{{ x.TotalWeight }}g</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
        </div>
        <!-- Volunteers -->
        <div class="divider">
            <h3 class="text-xl">Volunteers</h3>
        </div>
        <div>
            <table class="table table-compact w-full px-4">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Age</th>
                    <th>Location</th>
                    <th>Date Joined</th>
                  </tr>
                </thead>
                <tbody>
                  {% for x in volunteer_qs %}
                  <tr>
                    <th>{{ x.id }}</th>
                    <td>{{ x.firstName }} {{ x.lastName }} </td>
                    <td>{{ x.age}} </td>
                    <td>{{ x.addressFirstLine }}</td>
                    <td>{{ x.created_at }}</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
        </div>
    </div>
</div>
    
  </body>
</html>

app1/templates/layout.html
{% load tailwind_tags %}
{% load tailwind_filters %}

<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    {% tailwind_css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tw-elements/dist/css/index.min.css" />
    <link rel="stylesheet" href="{% static 'myCSS.css' %}">
  </head>
  <body>
    {% block content %} {% endblock %}
    <script src="{% static 'myJS.js' %}" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/tw-elements/dist/js/index.min.js"></script>
    <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="{% static 'Quagga_live.js' %}" defer></script>
    <script src="{% static 'libs/jquery-1.9.0.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'libs/quagga.js' %}"></script>

  </body>
  <!-- Bottom Nav -->
  <div class="btm-nav bg-base-200 z-50">
    <button onclick="location.href = '/'" class="{% if nbar == 'home' %}active{% endif %}">
      <i class="fa-solid fa-house"></i>
    </button>
    <button onclick="location.href = '/stock'" class="{% if nbar == 'stock' or nbar == 'scan_in' or nbar == 'scan_out' %}active{% endif %}">
      <i class="fa-solid fa-cart-shopping"></i>
    </button>
    <button onclick="location.href = '/people'" class="{% if nbar == 'people' or nbar == 'members' or nbar == 'add_member' %}active{% endif %}">
      <i class="fa-solid fa-users"></i>
    </button>
    <button onclick="location.href = '/reports'" class="{% if nbar == 'reports' %}active{% endif %}">
      <i class="fa-solid fa-bars"></i>
    </button>
  </div>
</html>

app1/templates/scan_in.html
{% extends "layout.html" %}
{% block title %}
Stock In
{% endblock %}
{% block content %}
<!-- {% load tailwind_filters %} -->
<div class="flex flex-col space-y-10">
  <!-- Heading -->
  <div class="flex justify-center align-middle text-3xl font-bold pt-3 space-x-2">
    <h1>Towcester</h1>
  </div>
  <!-- Content -->
  <div class="flex justify-center">
    <!-- Image Preview -->
    <div class="card bg-base-200 shadow-2xl w-96 flex justify-center">
      <div id="interactive" class="viewport">
          <canvas class="drawingBuffer w-96 absolute inset-0 z-20"></canvas>
          <video class="relative z-10 rounded-2xl" autoplay="true" preload="auto" src="" muted="true" playsinline="true"></video>
      </div>
    </div>
  </div>
  <!-- Info Cards -->
  <div class="">
    <div class="flex justify-center space-x-7">
      <div class="card bg-base-200 shadow-2xl w-96 flex flex-row justify-center items-center pb-4 px-2">
        <div class="form-control w-full max-w-xs">
          <label class="label">
            <span class="card-title">Barcode Lookup</span>
          </label>
          <form id="barcode_lookup" action="" onSubmit="test1()">
            <div class="flex flex-row items-center space-x-4">
              <input id="barcode_search" type="number" placeholder="Enter EAN"
                class="input input-bordered w-full max-w-xs" />
              <i id="mg_glass" class="fa-solid fa-magnifying-glass fa-lg cursor-pointer" onclick="BarcodeLookup()"></i>
              <!-- <i class="fa-solid fa-cart-plus fa-lg cursor-pointer" onclick="HTMLFormElement.prototype.submit.call($('#addProduct')[0])"></i> -->
            </div>
          </form>
          <form method="POST" action="/scan_in/">

            <div class="flex flex-col px-7 py-2 form-control">
              {% csrf_token %}
              {{ form|crispy }}
              <!-- <label class="label">
                  <span class="label-text-alt">Brand</span>
                </label>
                <input id="id_brand" type="text" placeholder="Enter Brand" class="input input-ghost w-full max-w-xs" />
                <label class="label">
                  <span class="label-text-alt">Product name</span>
                </label>
                <input id="id_name" type="text" placeholder="Enter Name" class="input input-ghost w-full max-w-xs" />
                <label class="label">
                  <span class="label-text-alt">Weight in grams</span>
                </label>
                <input id="id_weight" type="number" placeholder="Enter Weight (g)" class="input input-ghost w-full max-w-xs" />   
                <label class="label">
                  <span class="label-text-alt">Category</span>
                </label>
                <input id="id_category" type="text" placeholder="Enter Category" class="input input-ghost w-full max-w-xs" />
                <label class="label">
                  <span class="label-text-alt">Allergens</span>
                </label>
                <input id="id_allergens" type="text" placeholder="Enter Allergens separated by a comma" class="input input-ghost w-full max-w-xs" />
                <label class="label">
                  <span class="label-text-alt">Perishable ?</span>
                </label>
                <input type="checkbox" class="ml-4 checkbox checkbox-xs input-ghost" />  -->
              <button type="submit" value="submit" class="btn btn-primary mt-4">Add to Cart
                <i class="fa-solid fa-cart-plus cursor-pointer pl-2"></i>
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- Stock Info Cards -->
  <div class="flex justify-center space-x-7">
    <div class="card overflow-x-auto bg-base-200 shadow-2xl w-96 pb-4">
      <table class="table table-compact w-full px-4">
        <thead>
          <tr>
            <th>Name</th>
            <th>Category</th>
            <th>Perishable</th>
            <th>Weight</th>
            <th>EAN</th>
          </tr>
        </thead>
        <tbody>
          {% for x in product_qs_today %}
          <tr>
            <th>{{ x.name }}</th>
            <td>{{ x.brand }}</td>
            <td>{{ x.category_list.0 }},{{ x.category_list.1 }}</td>
            <td>{{ x.perishable }}</td>
            <td>{{ x.weight }}g</td>
            <td>{{ x.footprint }}per kg</td>
            <td>{{ x.barcode }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>


  <!-- Bottom Nav -->
  <div class="btm-nav bg-base-200">
    <button class="active">
      <i class="fa-solid fa-house"></i>
    </button>
    <button>
      <i class="fa-solid fa-cart-shopping"></i>
    </button>
    <button>
      <i class="fa-solid fa-users"></i>
    </button>
    <button>
      <i class="fa-solid fa-bars"></i>
    </button>
  </div>
  {% endblock %}